export const HOSPITAL_MANAGEMENT = {
    LOGIN: "/api/auth/hospital/login",
    SIGNUP: "/api/auth/hospital/signup",
    COMMON_STATS: "/api/hospital/common-stats",
    GET_ME: "/api/hospital/me",
    EDIT_HOSPITAL: `/api/hospital/hospitals`,
    GET_ALL_DOCTORS: `/api/hospital/doctors`,
    DOCTORS_TOGGLE: (id: string) => `/api/hospital/doctors/${id}/toggle`,
    PATIENTS_TOGGLE: (id: string) => `/api/hospital/patients/${id}/toggle`,
    PATIENT_ADD: `/api/hospital/patients`,
    DOCTOR_KYC: "/api/hospital/doctorKyc",
    GET_KYC_DOCTORS: "/api/hospital/doctors/kyc",
    DOCTOR_ACCEPT: (id: string) => `/api/hospital/doctors/${id}/accept`,
    DOCTOR_REJECT: (id: string) => `/api/hospital/doctors/${id}/reject`,
    DOCTOR_REVISION: (id: string) => `/api/hospital/doctors/${id}/revision`,
    GET_DOCTOR: (id: string) => `/api/hospital/doctors/${id}`,
    GET_PATIENT: (id: string) => `/api/hospital/patients/${id}`,
    EDIT_PATIENT: (id: string) => `/api/hospital/patients/${id}`,
    DOCTOR_ADD: "/api/hospital/doctors",
    GET_ALL_PATIENTS: "/api/hospital/patients",
    REAPPLY: "/api/hospital/reapply",
    DOCTOR_UPDATE: (id: string) => `/api/hospital/doctors/${id}`,
    GET_HOSPITAL_DATA: (id: string) => `/api/hospital/hospitals/${id}`,
    GET_HOSPITAL_DEPARTMENT: "/api/hospital/departments",
    CREATEDEPARTMENT: "/api/hospital/departments",
    DEPARTMENT_TOGGLE: (id: string) => `/api/hospital/departments/${id}/toggle`,
    UPDATE_DEPARTMENT: (id: string) => `/api/hospital/departments/${id}`,
    GET_QUALIFICATION: "/api/hospital/qualifications",
    CREATE_QUALIFICATION: "/api/hospital/qualifications",
    QUALIFICATION_TOGGLE: (id: string) => `/api/hospital/qualifications/${id}/toggle`,
    UPDATE_QUALIFICATION: (id: string) => `/api/hospital/qualifications/${id}`,
    GET_SPECIALIZATION: "/api/hospital/specializations",
    CREATE_SPECIALIZATION: "/api/hospital/specializations",
    SPECIALIZATION_TOGGLE: (id: string) => `/api/hospital/specializations/${id}/toggle`,
    UPDATE_SPECIALIZATION: (id: string) => `/api/hospital/specializations/${id}`,
    SELECTED_HOSPITAL: (id: string) => `/api/hospital/hospitals/${id}`,
    GET_LEAVE_DOCTORS:`/api/hospital/doctors/leaves`,
    UPDATE_LEAVE_STATUS: (id: string) => `/api/hospital/leaves/${id}/status`,
    GETSUBSCRIPTION:()=>`/api/hospital/subscription`,
    GETDEPSEPQULY:"/api/hospital/getdepsepquly",
    GETSUBCRITPIONPROTECTION:"/api/hospital/subscription/protection",
    SUBSCRIPTION_CURRENT: "/api/hospital/subscription/current",
    SUBSCRIPTION_UPGRADE: "/api/payment/subscription/upgrade",
    SUBSCRIPTION_ACTIVATE_DOWNGRADE: "/api/payment/subscription/activate-downgrade",
    SUBSCRIPTION_DOWNGRADE: "/api/hospital/subscription/downgrade",
    GETDASHBOARDSTATS:"/api/hospital/dashboard-stats",
    GET_DOCTOR_STATUS:"/api/hospital/getdoctorstatus",
    KYC_STATS:"/api/hospital/kyc-stats",
    GET_DOCTOR_SALARY_REQUEST:"/api/hospital/doctors-salary-requests",
    UPDATE_DOCTOR_SALARY_REQUEST_STATUS: (id: string) => `/api/hospital/doctors-salary-requests/${id}/status`,
        GET_WALLET:"/api/hospital/wallet",
        WITHDRAW:"/api/hospital/wallet/withdraw",
        GETREQCANCALATION:"/api/hospital/REQCansation",
        APPROVECANCALTION:(id:string)=>`/api/hospital/${id}/REQCansation`,
        REJECTCANCALTION:(id:string)=>`/api/hospital/${id}/REQCansation`
};
