export const HOSPITAL_MANAGEMENT = {
    LOGIN: "/api/auth/hospital/login",
    SIGNUP: "/api/auth/hospital/signup",
    GET_ME: "/api/hospital/getme",
    EDIT_HOSPITAL: (id: string) => `/api/hospital/hospitals/${id}`,
    GET_ALL_DOCTORS: `/api/hospital/getalldoctors`,
    DOCTORS_TOGGLE: (id: string) => `/api/hospital/doctorsToggle/${id}`,
    PATIENTS_TOGGLE: (id: string) => `/api/hospital/PatientsToggle/${id}`,
    PATIENT_ADD: `/api/hospital/patientAdd`,
    DOCTOR_KYC: "/api/hospital/doctorKyc",
    GET_KYC_DOCTORS: "/api/hospital/getkycdoctors",
    DOCTOR_ACCEPT: (id: string) => `/api/hospital/doctorAccept/${id}`,
    DOCTOR_REJECT: (id: string) => `/api/hospital/doctorReject/${id}`,
    DOCTOR_REVISION: (id: string) => `/api/hospital/doctorRevision/${id}`,
    GET_DOCTOR: (id: string) => `/api/hospital/doctors/${id}`,
    GET_PATIENT: (id: string) => `/api/hospital/patients/${id}`,
    EDIT_PATIENT: (id: string) => `/api/hospital/patientEdit/${id}`,
    DOCTOR_ADD: "/api/hospital/register-doctor",
    GET_ALL_PATIENTS: "/api/hospital/getallpatients",
    REAPPLY: "/api/hospital/reapply",
    DOCTOR_UPDATE: (id: string) => `/api/hospital/doctorEdit/${id}`,
    GET_HOSPITAL_DATA: (id: string) => `/api/hospital/hosptalData/${id}`,
    GET_HOSPITAL_DEPARTMENT: "/api/hospital/department",
    CREATEDEPARTMENT: "/api/hospital/createDepartment",
    DEPARTMENT_TOGGLE: (id: string) => `/api/hospital/departmentToggle/${id}`,
    UPDATE_DEPARTMENT: (id: string) => `/api/hospital/department/${id}`,
    GET_QUALIFICATION: "/api/hospital/qualification",
    CREATE_QUALIFICATION: "/api/hospital/createQualification",
    QUALIFICATION_TOGGLE: (id: string) => `/api/hospital/qualificationToggle/${id}`,
    UPDATE_QUALIFICATION: (id: string) => `/api/hospital/qualification/${id}`,
    GET_SPECIALIZATION: "/api/hospital/specialization",
    CREATE_SPECIALIZATION: "/api/hospital/createSpecialization",
    SPECIALIZATION_TOGGLE: (id: string) => `/api/hospital/specializationToggle/${id}`,
    UPDATE_SPECIALIZATION: (id: string) => `/api/hospital/specialization/${id}`,
};
