export const HOSPITAL_MANAGEMENT = {
    LOGIN: "/api/auth/hospital/login",
    SIGNUP: "/api/auth/hospital/signup",
    GET_ME: "/api/hospital/getme",
    EDIT_HOSPITAL: (id: string) => `/api/hospital/hospitals/${id}`,
    GET_ALL_DOCTORS: `/api/hospital/getalldoctors`,
    DOCTORS_TOGGLE: (id: string) => `/api/hospital/doctorsToggle/${id}`,
    PATIENTS_TOGGLE: (id: string) => `/api/hospital/PatientsToggle/${id}`,
    PATIENT_ADD: `/api/hospital/patientAdd`,
    DOCTOR_KYC: "/api/hospital/doctorKyc",
    GET_KYC_DOCTORS: "/api/hospital/getkycdoctors",
    DOCTOR_ACCEPT: (id: string) => `/api/hospital/doctorAccept/${id}`,
    DOCTOR_REJECT: (id: string) => `/api/hospital/doctorReject/${id}`,
    DOCTOR_REVISION: (id: string) => `/api/hospital/doctorRevision/${id}`,
    GET_DOCTOR: (id: string) => `/api/hospital/doctors/${id}`,
    GET_PATIENT: (id: string) => `/api/hospital/patients/${id}`,
    EDIT_PATIENT: (id: string) => `/api/hospital/patientEdit/${id}`,
    DOCTOR_ADD: "/api/hospital/register-doctor",
    GET_ALL_PATIENTS: "/api/hospital/getallpatients",
    REAPPLY: "/api/hospital/reapply",
    DOCTOR_UPDATE: (id: string) => `/api/hospital/doctorEdit/${id}`,
};
