export const AUTH_MANAGEMENT = {
    SEND_OTP: "/api/auth/send-otp",
    VERIFY_OTP: "/api/auth/verify-otp",
    SIGNUP: "/api/auth/signup",
    LOGIN: "/api/auth/login",
    REFRESH: "/api/auth/refresh",
    RESET_PASSWORD: "/api/auth/reset-password",
    LOGOUT: "/api/auth/logout",
    GOOGLE: "/api/auth/google",
    DOCTOR_LOGIN: "/api/auth/Doctor/login",
    HOSPITAL_LOGIN: "/api/auth/Hospital/login",
    SUPERADMIN_LOGIN: "/api/auth/Superadmin/login",
    HOSPITAL_SIGNUP: "/api/auth/hospital/signup",
    SELECTHOSPITLADOCTOR: "/api/auth/selectHospitals",
    REGISTORDOCTOR: "/api/auth/RegistorDoctor",
    GET_HOSPITAL_DEPARTMENTS: (hospitalId: string) => `/api/auth/hospitals/${hospitalId}/departments`,
    GET_HOSPITAL_QUALIFICATIONS: (hospitalId: string) => `/api/auth/hospitals/${hospitalId}/qualifications`,
    GET_HOSPITAL_SPECIALIZATIONS: (hospitalId: string) => `/api/auth/hospitals/${hospitalId}/specializations`,
};
